#!/usr/bin/env python3
"""score.py - drive scoring, summary, matrix, and review-queue assembly.

Modes:
  --framework <fw>                          -> emit <runs>/<fw>/scores.csv
  --framework <fw> --summary                -> also emit <findings>/<fw>/SUMMARY.md
  --framework <fw> --append-review-queue    -> append flagged rows to
                                               analysis/<review-queue-name>
  --matrix                                  -> emit analysis/<matrix-name>
  --end-of-run-report                       -> print final tallies

Output-path flags (default to v1 layout; v2 overrides them):
  --runs-dir <name>            default "runs"
  --findings-dir <name>        default "findings"
  --matrix-name <name>         default "matrix.csv"
  --review-queue-name <name>   default "REVIEW_QUEUE.md"

All inputs are read from <runs>/<fw>/probes/<D*>.txt. No web calls.
The scoring heuristics live in harness/lib/score_item.py and are NOT touched here.
"""
from __future__ import annotations
import argparse
import csv
import datetime as dt
import sys
from pathlib import Path

# Make `harness/lib` importable
ROOT_GUESS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_GUESS / "harness" / "lib"))
from score_item import score, RUBRICS  # noqa: E402

ITEM_IDS = sorted(RUBRICS.keys())

def score_framework(root: Path, fw: str, runs_dir: str) -> list[dict]:
    probe_dir = root / runs_dir / fw / "probes"
    rows: list[dict] = []
    for item_id in ITEM_IDS:
        # Convention: transcript path is <runs>/<fw>/probes/<item_id>.txt
        tpath = probe_dir / f"{item_id}.txt"
        s, c, ev, n = score(item_id, tpath)
        # Make evidence path repo-relative
        try:
            ev_rel = str(Path(ev).resolve().relative_to(root.resolve()))
        except Exception:
            ev_rel = ev
        rows.append({
            "item_id": item_id,
            "score": s,
            "confidence": c,
            "evidence_file": ev_rel,
            "notes": n,
        })
    return rows

def write_scores_csv(root: Path, fw: str, rows: list[dict], runs_dir: str) -> Path:
    out = root / runs_dir / fw / "scores.csv"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["item_id", "score", "confidence",
                                          "evidence_file", "notes"])
        w.writeheader()
        for r in rows:
            w.writerow(r)
    return out

def _read_ready(root: Path, fw: str, runs_dir: str) -> str | None:
    """Return a one-line time-to-ready summary from <runs>/<fw>/ready.txt, if any."""
    rp = root / runs_dir / fw / "ready.txt"
    if not rp.is_file():
        return None
    kv: dict[str, str] = {}
    for ln in rp.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" in ln:
            k, v = ln.split("=", 1)
            kv[k.strip()] = v.strip()
    status = kv.get("READY_STATUS", "?")
    ttr = kv.get("time_to_ready_seconds")
    if status == "READY" and ttr is not None:
        return f"READY in {ttr}s"
    if status == "FAILED":
        return f"FAILED to become ready within {kv.get('ceiling_seconds','?')}s (last code {kv.get('last_http_code','?')})"
    return status

def write_summary(root: Path, fw: str, rows: list[dict], runs_dir: str,
                  findings_dir: str) -> Path:
    install_log = root / runs_dir / fw / "install.log"
    flagged = [r for r in rows if r["confidence"] == "LOW" or r["score"] == "UNK"]
    insecure_high = [r for r in rows if r["score"] == "INSECURE"
                     and r["confidence"] == "HIGH"]
    ready = _read_ready(root, fw, runs_dir)

    out = root / findings_dir / fw / "SUMMARY.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    today = dt.date.today().isoformat()
    lines: list[str] = []
    lines.append(f"# {fw} - security defaults summary")
    lines.append("")
    lines.append(f"_Auto-generated by harness/score.py on {today}._")
    lines.append("")
    lines.append("## Install / readiness")
    lines.append(f"- Script: `frameworks/{fw}/install.sh`")
    lines.append(f"- Log: `{runs_dir}/{fw}/install.log` "
                 f"({'present' if install_log.is_file() else 'MISSING'})")
    lines.append(f"- Readiness: {ready if ready is not None else 'no ready.txt (wait step not run)'}")
    if install_log.is_file():
        tail = install_log.read_text(encoding='utf-8', errors='replace').splitlines()[-5:]
        lines.append("- Last 5 log lines:")
        for t in tail:
            lines.append(f"  > `{t}`")
    lines.append("")
    lines.append("## Headline posture")
    n_ins = sum(1 for r in rows if r["score"] == "INSECURE")
    n_sec = sum(1 for r in rows if r["score"] == "SECURE")
    n_warn = sum(1 for r in rows if r["score"] == "WARNS")
    n_unk = sum(1 for r in rows if r["score"] == "UNK")
    lines.append(f"- INSECURE: {n_ins} | WARNS: {n_warn} | SECURE: {n_sec} | UNK: {n_unk}")
    lines.append("")
    lines.append("## D7.2 gap score")
    lines.append("- TBD: computed at matrix step (count of INSECURE items with a SECURE option in docs).")
    lines.append("")
    lines.append("## Spot-check transcripts (HIGH-confidence INSECURE)")
    if not insecure_high:
        lines.append("- (none)")
    else:
        for r in insecure_high[:3]:
            lines.append(f"- `{r['evidence_file']}` ({r['item_id']}): {r['notes']}")
    lines.append("")
    lines.append("## NEEDS HUMAN REVIEW")
    if not flagged:
        lines.append("No items flagged - all scores HIGH confidence with clean evidence.")
    else:
        lines.append(f"- {len(flagged)} item(s) flagged (LOW confidence or UNK).")
        lines.append("")
        lines.append("| item | score | conf | transcript | what to check |")
        lines.append("|------|-------|------|------------|----------------|")
        for r in flagged:
            lines.append(f"| {r['item_id']} | {r['score']} | {r['confidence']} | "
                         f"`{r['evidence_file']}` | {r['notes']} |")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return out

def append_review_queue(root: Path, fw: str, rows: list[dict], rq_name: str) -> Path:
    out = root / "analysis" / rq_name
    out.parent.mkdir(parents=True, exist_ok=True)
    flagged = [r for r in rows if r["confidence"] == "LOW" or r["score"] == "UNK"]
    if not out.is_file():
        out.write_text("# Review Queue\n\n", encoding="utf-8")
    block = [f"\n## {fw}"]
    if not flagged:
        block.append("- (no items flagged)")
    else:
        block.append("| item | score | conf | transcript | what to check |")
        block.append("|------|-------|------|------------|----------------|")
        for r in flagged:
            block.append(f"| {r['item_id']} | {r['score']} | {r['confidence']} | "
                         f"`{r['evidence_file']}` | {r['notes']} |")
    with out.open("a", encoding="utf-8") as f:
        f.write("\n".join(block) + "\n")
    return out

def build_matrix(root: Path, runs_dir: str, matrix_name: str) -> Path:
    out = root / "analysis" / matrix_name
    out.parent.mkdir(parents=True, exist_ok=True)
    frameworks_dir = root / "frameworks"
    # Only frameworks that actually have a run dir in THIS runs tree are in scope.
    frameworks = sorted(
        p.name for p in frameworks_dir.iterdir()
        if p.is_dir() and (root / runs_dir / p.name).is_dir()
    )
    rows: list[dict] = []
    for fw in frameworks:
        scores_csv = root / runs_dir / fw / "scores.csv"
        if not scores_csv.is_file():
            for item_id in ITEM_IDS:
                rows.append({"framework": fw, "item_id": item_id,
                             "score": "UNK", "confidence": "LOW",
                             "evidence_file": "",
                             "notes": "no scores.csv (framework not scored)"})
            continue
        with scores_csv.open(encoding="utf-8") as f:
            for r in csv.DictReader(f):
                rows.append({"framework": fw, **r})
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["framework", "item_id", "score",
                                          "confidence", "evidence_file", "notes"])
        w.writeheader()
        w.writerows(rows)
    return out

def end_of_run_report(root: Path, matrix_name: str, rq_name: str) -> None:
    matrix = root / "analysis" / matrix_name
    if not matrix.is_file():
        print(f"end-of-run: {matrix_name} missing - run --matrix first")
        return
    by_score: dict[str, int] = {}
    by_conf: dict[str, int] = {}
    insecure_low: list[tuple[str, str]] = []
    insecure_high: list[tuple[str, str, str]] = []
    fw_seen: set[str] = set()
    fw_no_scores: set[str] = set()
    with matrix.open(encoding="utf-8") as f:
        for r in csv.DictReader(f):
            fw_seen.add(r["framework"])
            if "no scores.csv" in r.get("notes", ""):
                fw_no_scores.add(r["framework"])
            by_score[r["score"]] = by_score.get(r["score"], 0) + 1
            by_conf[r["confidence"]] = by_conf.get(r["confidence"], 0) + 1
            if r["score"] == "INSECURE" and r["confidence"] == "LOW":
                insecure_low.append((r["framework"], r["item_id"]))
            if r["score"] == "INSECURE" and r["confidence"] == "HIGH":
                insecure_high.append((r["framework"], r["item_id"], r.get("notes", "")))
    rq = root / "analysis" / rq_name
    rq_size = rq.read_text(encoding="utf-8").count("\n| D") if rq.is_file() else 0
    total = sum(by_score.values())
    print("==================== END-OF-RUN REPORT ====================")
    print(f"Matrix: analysis/{matrix_name}")
    print(f"Frameworks scored: {len(fw_seen)} "
          f"(no scores.csv: {sorted(fw_no_scores) or 'none'})")
    print(f"Total checklist rows: {total}")
    print(f"By score: {by_score}")
    print(f"By confidence: {by_conf}")
    print(f"Review-queue rows: {rq_size}")
    # The two failure modes a human must spot-check, BOTH listed (v1 fix):
    #  - INSECURE + LOW  : uncertain insecure claims
    #  - INSECURE + HIGH : confident insecure claims (a fabricated one here was the
    #                      exact v1 bug the old report could not surface).
    print(f"HIGH-impact LOW-confidence (INSECURE + LOW): {len(insecure_low)}")
    for fw, item in insecure_low:
        print(f"  - {fw}/{item}")
    print(f"HIGH-confidence INSECURE (spot-check EVERY one): {len(insecure_high)}")
    for fw, item, note in insecure_high:
        print(f"  - {fw}/{item}: {note}")
    print()
    print(f"Human: review `analysis/{rq_name}` first, then spot-check every "
          "HIGH-confidence INSECURE row listed above against its transcript.")
    print("===========================================================")

def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--framework")
    ap.add_argument("--summary", action="store_true")
    ap.add_argument("--append-review-queue", action="store_true")
    ap.add_argument("--matrix", action="store_true")
    ap.add_argument("--end-of-run-report", action="store_true")
    ap.add_argument("--runs-dir", default="runs")
    ap.add_argument("--findings-dir", default="findings")
    ap.add_argument("--matrix-name", default="matrix.csv")
    ap.add_argument("--review-queue-name", default="REVIEW_QUEUE.md")
    args = ap.parse_args(argv)
    root = Path(args.root).resolve()

    if args.end_of_run_report:
        end_of_run_report(root, args.matrix_name, args.review_queue_name); return 0
    if args.matrix:
        out = build_matrix(root, args.runs_dir, args.matrix_name)
        print(f"matrix -> {out}"); return 0
    if not args.framework:
        ap.error("need --framework (or --matrix / --end-of-run-report)")

    rows = score_framework(root, args.framework, args.runs_dir)
    out = write_scores_csv(root, args.framework, rows, args.runs_dir)
    print(f"scores -> {out}")
    if args.summary:
        s = write_summary(root, args.framework, rows, args.runs_dir, args.findings_dir)
        print(f"summary -> {s}")
    if args.append_review_queue:
        rq = append_review_queue(root, args.framework, rows, args.review_queue_name)
        print(f"review-queue appended -> {rq}")
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
